### ISSUE TITLE
White fonts at the simple task editor

### ISSUE THREAD

**Issue by dmuiX** [ilindaniel/sn-theme-evernote-dark#1]
First of all thanks a lot for your theme. I use it regularly =)
It happens that in the simple task editor the font color is black. It should be white for better readability. I don't know if its possible to change it?

**Comment by ilindaniel** [comment]
Hey @dmuiX , can you send me some screenshots please and what OS you are running?
It's looking fine on my side.
![Screenshot_2021-03-28_165422](https://user-images.githubusercontent.com/25451549/112756601-4c487880-8fe6-11eb-994c-6b7d22bf2344.png)
![Screenshot_2021-03-28_165431](https://user-images.githubusercontent.com/25451549/112756602-4ce10f00-8fe6-11eb-9379-b124ec53d260.png)

**Comment by dmuiX** [comment]
I am using android. Haven't tested it on other oses. I will try last time the app told me it's a security lock so I cannot make screenshots.. .

**Comment by ilindaniel** [comment]
> I am using android. Haven't tested it on other oses. I will try last time the app told me it's a security lock so I cannot make screenshots.. .

Try to make a photo with another phone/camera if possible.

**Comment by dmuiX** [comment]
Finally the new update they made it possible to make screenshots again so here it is. As you can see the font color is black on android. In the desktop version of my mac its correct. What are you using? Ios?

**Comment by dmuiX** [comment]
![Uploading Screenshot_20210403-003632_Standard Notes.jpg…]()

**Comment by dmuiX** [comment]
![20210403_004521](https://user-images.githubusercontent.com/19862760/113459472-e27d0400-9415-11eb-9bae-c754bac4b030.jpg)

**Comment by ilindaniel** [comment]
Hey @dmuiX , it seems like Simple Task Editor extension hardcodes `--sn-stylekit-foreground-color:` to `black`, so I tried to overwrite it via a `!important` css-rule with another color, however that didn't work out well. I guess everytime the extension is loaded, it overwrites whatever sn-stylekit variable was set before by the theme and sets it back to black.

However there are some other dark themes by the community, if you're interested:
https://github.com/jonhadfield/awesome-standard-notes#themes

Gruvbox theme by Christian Hans seems to handle the colors for the Simple Task Editor well, however I didn't have enough time to check how he accomplished that. I will have a look in the future.

**Comment by dmuiX** [comment]
Yeah I am using this theme https://github.com/ceiphr/sn-yaru-theme and here the fonts are also white. 
Okay thanks so far for looking at it.. Would like to see it soon as it's a nice theme and I love to have alternatives where I can switch =).
